# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: amitkuamrdube/kitchen-terraform:latest
    env : 
      GOOGLE_APPLICATION_CREDENTIALS: "my-first-project-298218-7e25767dcc93.json"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # creating config file with the key set a secret
      - id : config-file-creation
        name : setup service account file
        run : |- 
          cat > my-first-project-298218-7e25767dcc93.json <<-EOF
            ${{ secrets.SA_KEY }}
          EOF
      # setting up gcloud with the key
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SA_KEY }}      
#      - name : Terraform Execution
#        run : |
#          terraform init
#          terraform plan
#          terraform apply --auto-approve
      # Running Kitchen Commands
      - name : Kitchen Execution 
        run : |
          kitchen create
          kitchen converge
          kitchen verify
      # Running Kitchen Destroy
      - name : Kitchen Destroy
        run : kitchen destroy